apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-synchronizer
  labels:
    app: ip-app-synchronizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-app-synchronizer
      GPBApp: ip-app-synchronizer
      GPBAppVer: gpb
      GPBEnvironment: gpb1
  template:
    metadata:
      labels:
        app: ip-app-synchronizer
        GPBApp: ip-app-synchronizer
        GPBAppVer: gpb
        GPBEnvironment: gpb1
    spec:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ip-app-synchronizer
          image: superhero86/ip-app-synchronizer:9.5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8090
          livenessProbe:
            httpGet:
              port: 8090
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8090
            initialDelaySeconds: 30
            periodSeconds: 3
            timeoutSeconds: 30
          env:
            - name: IP_APP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_HOST
                  name: ip-app-db-configmap
            - name: IP_APP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_PORT
                  name: ip-app-db-configmap
            - name: IP_APP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_NAME
                  name: ip-app-db-configmap
            - name: IP_APP_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_USERNAME
                  name: ip-app-db-configmap
            - name: IP_APP_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: IP_APP_DB_PASSWORD
                  name: ip-app-db-configmap
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
