apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-redict
  labels:
    app: ip-app-redict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-app-redict
      GPBApp: ip-app-redict
      GPBAppVer: gpb
      GPBEnvironment: gpb1
  template:
    metadata:
      labels:
        app: ip-app-redict
        GPBApp: ip-app-redict
        GPBAppVer: gpb
        GPBEnvironment: gpb1
    spec:
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ip-app-redict
          image: superhero86/redict:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 6379
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
