apiVersion: v1
kind: PersistentVolume
metadata:
  name: ip-app-logic-templates-pv-95
spec:
  capacity:
    storage: 10Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce 
  nfs:
    server: 192.168.57.4
    path: "/nfs/ip_data/templates"
