apiVersion: v1
kind: PersistentVolume
metadata:
  name: ip-app-gateway-web-static-pv-95
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.57.4
    path: "/nfs/ip_data/static"
